import {
    Button,
    VerticalBox,
    ScrollView,
    Palette,
} from "std-widgets.slint";
import { ListValue } from "list-value.slint";
import { ValueType } from "value-type.slint";

export struct ListDesc { title: string, description: string, value: string, value-type: ValueType, key: string }

export component ValueList {

    in property <[ListDesc]> values;

    ScrollView {
        VerticalBox {
            spacing: 0;
            for value[index] in values: VerticalBox {
                spacing: 0;
                padding: 0;
                if index > 0: Rectangle {
                    height: 1px;
                    background: Palette.control-foreground;
                    opacity: 0.2;
                }

                ListValue {
                    title: value.title;
                    description: value.description;
                    value: value.value;
                    value-type: value.value-type;
                    key: value.key;
                }
            }
        }
    }
}
